List<String> dogNames = [
  'Samoyed',
  'American Eskimo',
  'Great Pyrenees',
  'Akita',
  'Husky',
  'Bolognese',
  'Kuvasz',
  'Labrador Retriever',
  'German Shepherd',
  'Golden Retriever',
  'Bulldog',
  'Poodle',
  'Beagle',
  // Danh sách tiếp theo có thể thêm vào đây
  'Alaskan Malamute',
  'Shiba Inu',
  'Siberian Husky',
  'Border Collie',
  'Australian Shepherd',
  'Boxer',
  'Dachshund',
  'Pomeranian',
  'Corgi',
  'Rottweiler',
  'Doberman Pinscher',
  'Bernese Mountain Dog',
  'Newfoundland',
  'Shih Tzu',
  'Yorkshire Terrier',
  'Chihuahua',
  'Boston Terrier',
  'Maltese',
  'Weimaraner',
  'Saint Bernard',
  'Cocker Spaniel',
  'Basset Hound',
  'Mastiff',
  'Pug',
  'Rhodesian Ridgeback',
  'Great Dane',
  'Papillon',
  'Havanese',
  'Bichon Frise',
  'Whippet',
  'Greyhound',
  'Irish Wolfhound',
  'Chinese Crested',
  'Pekingese',
  'Dalmatian',
  'Collie',
  'Shetland Sheepdog',
  'Bull Terrier',
  'Miniature Schnauzer',
  'Australian Terrier',
  'Scottish Terrier',
  'English Setter',
  'Pointer',
  'Borzoi',
  'Briard',
  'Afghan Hound',
  'Basenji',
  'Chinese Shar-Pei',
  'Akita Inu',
  'English Bulldog',
  'French Bulldog',
  'Cavalier King Charles Spaniel',
  'Whippet',
  'West Highland White Terrier',
  'Bichon Frise',
  'Bloodhound',
  'Bullmastiff',
  'Briard',
  'Bouvier des Flandres',
  'Australian Cattle Dog',
  'American Cocker Spaniel',
  'English Cocker Spaniel',
  'Cane Corso',
  'Catahoula Leopard Dog',
  'Chesapeake Bay Retriever',
  'Clumber Spaniel',
  'Coton de Tulear',
  'Curly-Coated Retriever',
  'Finnish Spitz',
  'German Pinscher',
  'Glen of Imaal Terrier',
  'Greater Swiss Mountain Dog',
  'Ibizan Hound',
  'Irish Setter',
  'Irish Terrier',
  'Irish Water Spaniel',
  'Kerry Blue Terrier',
  'Lhasa Apso',
  'Lowchen',
  'Maltese',
  'Manchester Terrier',
  'Norwegian Elkhound',
  'Norwich Terrier',
  'Nova Scotia Duck Tolling Retriever',
  'Old English Sheepdog',
  'Otterhound',
  'Petit Basset Griffon Vendeen',
  'Pharaoh Hound',
  'Plott',
  'Portuguese Water Dog',
  'Pyrenean Shepherd',
  'Redbone Coonhound',
  'Spinone Italiano',
  'Swedish Vallhund',
  'Tibetan Mastiff',
  'Tibetan Spaniel',
  'Tibetan Terrier',
  'Treeing Walker Coonhound',
  'Vizsla',
  'Wirehaired Pointing Griffon',
  'Xoloitzcuintli',
  'Australian Terrier',
  'Border Terrier',
  'Irish Terrier',
  'Scottish Terrier',
  'Bedlington Terrier',
  'Kerry Blue Terrier',
  'Lakeland Terrier',
  'Norfolk Terrier',
  'Norwich Terrier',
  'Sealyham Terrier',
  'Silky Terrier',
  'Skye Terrier',
  'West Highland White Terrier',
  'Affenspinscher',
  'Brussels Griffon',
  'Cairn Terrier',
  'Cesky Terrier',
  'Dandie Dinmont Terrier',
  'Japanese Terrier',
  'Manchester Terrier',
  'Miniature Bull Terrier',
  'Miniature Schnauzer',
  'Russian Toy Terrier',
  'Scottish Terrier',
  'Scottish Terrier',
  'Scottish Terrier',
  'Scottish Terrier',
  'Scottish Terrier',
  'Sealyham Terrier',
  'Skye Terrier',
  'Skye Terrier',
  'Skye Terrier',
  'Skye Terrier',
  'Skye Terrier',
  'Welsh Terrier',
  'American Eskimo Dog',
  'Bichon Frise',
  'Bolognese',
  'Boston Terrier',
  'Bulldog',
  'Cavalier King Charles Spaniel',
  'Chihuahua',
  'Chinese Crested',
  'Coton de Tulear',
  'French Bulldog',
  'Havanese',
  'Italian Greyhound',
  'Japanese Chin',
  'Maltese',
  'Manchester Terrier',
  'Miniature Pinscher',
  'Papillon',
  'Pekingese',
  'Pomeranian',
  'Poodle',
  'Pug',
  'Shih Tzu',
  'Toy Fox Terrier',
  'Yorkshire Terrier',
  'Affenpinscher',
  'Brussels Griffon',
  'Cavalier King Charles Spaniel',
  'Chihuahua',
  'Chinese Crested',
  'English Toy Spaniel',
  'Havanese',
  'Italian Greyhound',
  'Japanese Chin',
  'Maltese',
  'Manchester Terrier',
  'Miniature Pinscher',
  'Papillon',
  'Pekingese',
  'Pomeranian',
  'Poodle',
  'Pug',
  'Shih Tzu',
  'Silky Terrier',
  'Toy Fox Terrier',
  'Yorkshire Terrier',
  'Affenpinscher',
  'Brussels Griffon',
  'Cavalier King Charles Spaniel',
  'Chihuahua',
  'Chinese Crested',
  'English Toy Spaniel',
  'Havanese',
  'Italian Greyhound',
  'Japanese Chin',
  'Maltese',
  'Manchester Terrier',
  'Miniature Pinscher',
  'Papillon',
  'Pekingese',
  'Pomeranian',
  'Poodle',
  'Pug',
  'Shih Tzu',
  'Silky Terrier',
  'Toy Fox Terrier',
  'Yorkshire Terrier',
];